#!/bin/bash

# The purpouse of this script is to run the Telegram For Linux Installer, nothing else.
# Following KISS.

# Telegram will be/was download here
DownloadDir="/dev/shm/Telegram"
# From here
DownloadURL="https://telegram.org/dl/desktop/linux"
# Named as
TelegramCompressed="Telegram.tar.xz"
# DownloadURL + TelegramCompressed = Dest!
Dest="$DownloadDir/$TelegramCompressed"
# Instalation Directory
InstallDir="/opt"

echo "==== Running TelegramForLinux Installer ===="
sh /usr/local/bin/TelegramForLinuxInstaller.sh

